from datetime import date


def _source(con, title, url):
    row = con.execute("SELECT id FROM sources WHERE url=?", (url,)).fetchone()
    if row:
        return row[0]
    return con.execute("INSERT INTO sources(title,publisher,url,accessed,source_type,notes) VALUES(?,?,?,?,?,?)",
        (title, "Ross-Tech", url, date.today().isoformat(), "Oficial", "Ross-Tech Wiki - Auto-Scan DTC expansion 2")).lastrowid


def _upsert(con, code, title, symptoms, causes, component, location, params, expected, path, diagnosis, repair, replacement, severity, source_id):
    row = con.execute("SELECT id FROM dtcs WHERE UPPER(code)=?", (code.upper(),)).fetchone()
    description = title
    values=(title,description,symptoms,causes,diagnosis,repair,severity,1,source_id,component,location,params,expected,path,replacement)
    if row:
        con.execute("UPDATE dtcs SET title=?,description=?,symptoms=?,causes=?,diagnosis=?,repair=?,severity=?,verified=?,source_id=?,component=?,component_location=?,vcds_parameters=?,expected_values=?,test_path=?,replacement_steps=? WHERE id=?", values+(row[0],))
    else:
        con.execute("INSERT INTO dtcs(code,title,description,symptoms,causes,diagnosis,repair,severity,verified,source_id,component,component_location,vcds_parameters,expected_values,test_path,replacement_steps) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)", (code,)+values)


def install(con):
    data = [
      ("P0101","MAF G70 - semnal implauzibil","Pierdere putere; ralanti neregulat.","G70; aer fals după MAF; filtru/admisie/evacuare restricționată; mase/cablaj.","G70 Mass Air Flow Sensor","Pe conducta de admisie după filtrul de aer.","MAF actual/target; la TDI vechi se poate verifica MVB 003.","Valoarea trebuie să reacționeze coerent cu sarcina; compară actual cu specified unde există.","[01-Engine] > Measuring Blocks/Advanced Measuring Values > MAF","Verifică filtrul, admisia dintre MAF și turbo, cablajul/masele; log MAF sub sarcină; caută și probleme mecanice care reduc debitul.","Repară scurgerile/restricțiile sau cablajul; înlocuiește G70 numai după confirmare.","După G70: șterge DTC, verifică MAF live și fă test drive/log.","Mediu","https://wiki.ross-tech.com/wiki/index.php/16485/P0101/000257"),
      ("P0234","Boost pressure regulation - overboost","MIL; presiune prea mare; limp mode/pierdere putere.","Furtunuri greșite/blocate; N75; G31; geometrie/turbo blocat.","N75/G31/turbocompresor","N75 și actuatorul sunt în circuitul de comandă turbo; G31 pe traseul de presiune.","Boost specified/actual; N75 duty; actuator position unde există.","Actual trebuie să urmărească target fără suprapresiune persistentă.","[01-Engine] > Advanced Measuring Values; Output Tests/Basic Settings unde sunt suportate","Inspectează furtunurile/vacuumul; log target vs actual; Output Test; verifică N75, G31 și cursa actuatorului/geometriei.","Repară controlul presiunii; curăță/repară geometria sau înlocuiește componenta confirmată.","După turbo/actuator/N75: verifică Basic Settings disponibil, log boost și rescanare.","Ridicat","https://wiki.ross-tech.com/index.php/16618/P0234/000564"),
      ("P0236","G31 boost/manifold pressure - semnal implauzibil","Putere redusă; accelerație slabă; MIL.","Pierderi boost/intercooler; coliere; cablaj G31; G31; actuator V465.","G31 / V465 / charge-air system","G31 este pe traseul de aer presurizat/admisie, poziția exactă diferă după motor.","Boost/manifold/barometric pressure; actuator position.","Ross-Tech notează că DTC poate apărea când ECU vede o diferență de presiune de peste 75 mbar între senzorii comparați.","[01-Engine] > Advanced Measuring Values > pressure sensors","Verifică traseul/intercoolerul, cablajul și conectorul G31; compară senzorii cu contact pus/motor oprit și apoi sub sarcină.","Repară scurgerea/cablajul sau înlocuiește G31/V465 dacă testele confirmă.","După înlocuire: verifică plausibility la contact și log sub sarcină.","Ridicat","https://wiki.ross-tech.com/wiki/index.php/16620/P0236/000566"),
      ("P0671","Cylinder 1 glow plug circuit - electrical fault","Preîncălzire absentă; pornire grea la rece.","Bujie incandescentă cilindrul 1 sau cablaj defect.","Q10 glow plug cylinder 1","În chiulasă la cilindrul 1; accesul diferă după motor.","Glow plug status/current dacă ECU oferă valori; verificare electrică directă.","Comportament/rezistență comparabilă cu celelalte bujii de același tip.","[01-Engine] > Fault Codes / Advanced Measuring Values dacă sunt disponibile","Inspectează mufa/cablajul; măsoară bujia conform tipului și compară cu celelalte; verifică modulul de bujii dacă sunt mai multe cilindri afectați.","Repară cablajul sau înlocuiește bujia confirmată.","După înlocuire: șterge DTC și verifică pornirea la rece/curentul dacă este disponibil.","Mediu","https://wiki.ross-tech.com/wiki/index.php/17055/P0671/001649"),
      ("P2002","DPF bank 1 - eficiență/malfunction","MIL; posibil avertizare DPF/regenerări nereușite.","G450 defect sau DPF încărcat/defect.","DPF + G450","DPF în evacuare; G450 conectat la presiunea înainte/după filtru.","Differential pressure; soot mass calculated/measured; ash load; EGT; regeneration status.","Presiunea trebuie să fie plauzibilă; soot load trebuie să fie sub limita permisă înainte de regenerare forțată.","[01-Engine] > Advanced Measuring Values; Basic Settings/Adaptation pentru regenerare doar conform ECU","Verifică mai întâi G450 și furtunașele; citește soot/ash/EGT; stabilește de ce regenerarea nu se finalizează. Nu forța regenerarea peste limita specificată.","Repară G450/furtunașe dacă sunt cauza; regenerează numai dacă încărcarea și condițiile permit; înlocuiește DPF dacă este peste limită/defect.","După G450/DPF: adaptation/reset doar conform controllerului și piesei; verifică differential pressure și Auto-Scan.","Ridicat","https://wiki.ross-tech.com/wiki/index.php/18434/P2002/008194"),
      ("P2015","Intake manifold flap position - implausible","MIL; pierdere putere.","Clapetă galerie; V157 blocat/defect; software ECU; cablaj/conector; G336.","V157/G336 intake manifold runner","Pe galeria de admisie; motorul/senzorul pot fi integrate în aceeași unitate.","Intake manifold flap specified/actual/position unde există.","Poziția trebuie să urmărească comanda fără blocare sau semnal implauzibil.","[01-Engine] > Output Tests / Basic Settings unde controllerul suportă","Inspectează mecanismul și depunerile; cablaj; Output Test; Basic Setting dacă este disponibil; verifică aplicabilitatea software/TSB pentru motor.","Repară cablajul/mecanismul; uneori este necesară înlocuirea galeriei complete.","După V157/galerie: Output Test și Basic Setting dacă ECU suportă; unele configurații necesită unealtă de fabrică.","Mediu","https://wiki.ross-tech.com/wiki/index.php/18447/P2015/008213"),
      ("P2263","Turbo/supercharger boost system - performance","MIL; posibil pierdere putere.","Furtunuri conectate greșit/blocate/scurse; N75; pe unele motoare G581/actuator; alte cauze mecanice.","N75 / turbo actuator / boost system","În circuitul turbo și vacuum/charge-air.","Boost target/actual; N75; actuator/G581 position unde există.","Actual și poziția actuatorului trebuie să urmărească cererea fără abateri persistente.","[01-Engine] > Advanced Measuring Values / Output Tests","Verifică furtunurile, N75 și actuatorul; log boost; dacă există G581 verifică semnalul/poziția; apoi verifică mecanic turbo.","Repară scurgerile/controlul sau componenta confirmată.","După actuator/turbo: calibrare/Basic Setting dacă ECU oferă, apoi log și rescanare.","Ridicat","https://wiki.ross-tech.com/wiki/index.php/18695/P2263/008803"),
      ("P2563","Turbo boost control position sensor - implausible","MIL; pierdere putere.","Cablaj G581; G581; actuator/geometrie blocată; carbon; vacuum/N75; rar ECU.","G581 / turbo actuator","Integrat/asociat actuatorului turbo, în funcție de turbină.","Charge pressure actuator position specified/actual; boost target/actual; N75/vacuum.","Poziția trebuie să fie plauzibilă și să urmărească cererea pe toată cursa.","[01-Engine] > Advanced Measuring Values / Basic Settings actuator dacă este disponibil","Verifică vacuumul, cablajul și cursa actuatorului; compară specified/actual; verifică depuneri și reglajul mecanic înainte de turbo complet.","Repară vacuum/cablaj/actuator; curăță sau înlocuiește turbo dacă mecanismul este blocat/uzat.","După actuator/turbo: Basic Setting/calibrare dacă este suportată și log boost/position.","Ridicat","https://wiki.ross-tech.com/wiki/index.php/18995/P2563/009571"),
      ("00003","Control Module - defective/basic setting/adaptation","Depinde de modul; funcții indisponibile sau DTC după înlocuire/codare.","Modul defect/software sau Basic Setting/Adaptation lipsă, în funcție de subtipul textului DTC.","Control module indicat de adresa Auto-Scan","Modulul care stochează DTC; locația se stabilește din mașina/modulul selectat.","Part No/Component/Coding + measuring values specifice modulului.","Trebuie interpretat împreună cu textul complet al DTC și modulul care îl stochează.","Modulul din Auto-Scan > Fault Codes; apoi Basic Settings/Adaptation/Coding după caz","Nu condamna modulul doar după 00003. Citește textul complet: Defective vs No/Incorrect Basic Setting/Adaptation; verifică software, coding și alimentări.","Corectează basic setting/adaptation/coding dacă aceasta este varianta; înlocuiește modulul numai dacă diagnosticul confirmă defect intern.","După modul nou: coding/adaptation/basic setting conform modulului și platformei; Auto-Scan final.","Ridicat","https://wiki.ross-tech.com/wiki/index.php/00003")
    ]
    for code,title,symptoms,causes,component,location,params,expected,path,diagnosis,repair,replacement,severity,url in data:
        sid=_source(con, f"Ross-Tech {code}", url)
        _upsert(con,code,title,symptoms,causes,component,location,params,expected,path,diagnosis,repair,replacement,severity,sid)

    # Cylinder-specific glow plug faults share the verified Ross-Tech pattern.
    base=_source(con,"Ross-Tech glow plug circuit family","https://wiki.ross-tech.com/wiki/index.php/Category:Fault_Codes")
    for cyl,code in [(2,"P0672"),(3,"P0673"),(4,"P0674"),(5,"P0675")]:
        _upsert(con,code,f"Cylinder {cyl} glow plug circuit - electrical fault","Pornire grea la rece / preîncălzire afectată.","Bujie incandescentă sau cablaj; dacă sunt multe cilindri, verifică și modulul/alimentarea.",f"Glow plug cylinder {cyl}",f"În chiulasă la cilindrul {cyl}; poziția exactă depinde de motor.","Glow plug status/current unde ECU oferă; verificare electrică directă.","Compară cu celelalte bujii de același tip.","[01-Engine] > Fault Codes / Advanced Measuring Values","Verifică mufa, cablajul și bujia; dacă sunt mai multe DTC simultan verifică modulul și alimentarea comună.","Repară cablajul sau înlocuiește bujia confirmată.","Șterge DTC și verifică pornirea la rece.","Mediu",base)
    con.commit()
