from __future__ import annotations

import re


# Înregistrările detaliate KID sunt deja în română. Lista de mai jos este
# utilizată pentru titlurile standard OBD și denumirile VCDS rămase în engleză.
_PHRASES: tuple[tuple[str, str], ...] = (
    ("Hybrid/EV Battery Pack", "pachet baterie hibridă/vehicul electric"),
    ("Hybrid Battery Pack", "pachet baterie hibridă"),
    ("Electric Vehicle Battery Pack", "pachet baterie vehicul electric"),
    ("High Voltage Interlock Loop", "buclă de interblocare pentru înaltă tensiune"),
    ("High Voltage", "înaltă tensiune"),
    ("Low Voltage", "tensiune scăzută"),
    ("Circuit Low Voltage", "tensiune scăzută în circuit"),
    ("Circuit High Voltage", "tensiune ridicată în circuit"),
    ("Fuel Cell Stack", "ansamblu pile de combustie"),
    ("Fuel Cell", "pilă de combustie"),
    ("Alternative Fuel", "combustibil alternativ"),
    ("Fuel Volume Regulator", "regulator volum combustibil"),
    ("Fuel Shutoff Valve", "supapă oprire combustibil"),
    ("Reductant Heater", "încălzitor agent reducător"),
    ("Reductant Injection", "injecție agent reducător"),
    ("Reductant Level", "nivel agent reducător"),
    ("Reductant Pressure", "presiune agent reducător"),
    ("Reductant Temperature", "temperatură agent reducător"),
    ("Reductant Leakage", "scurgere agent reducător"),
    ("Selective Catalytic Reduction", "reducere catalitică selectivă"),
    ("Exhaust Aftertreatment", "post-tratare gaze de eșapament"),
    ("Exhaust Gas Temperature", "temperatură gaze de eșapament"),
    ("Particulate Matter Sensor", "senzor particule"),
    ("Active Grille Air Shutter", "obturator activ grilă radiator"),
    ("Battery Energy Control Module", "unitate de comandă energie baterie"),
    ("Battery Charger", "încărcător baterie"),
    ("On-Board Charger", "încărcător de bord"),
    ("Battery Cell", "celulă baterie"),
    ("Battery Pack", "pachet baterie"),
    ("State of Charge", "stare de încărcare"),
    ("State of Health", "stare de sănătate"),
    ("Isolation Fault", "defect de izolație"),
    ("Thermal Management", "management termic"),
    ("Drive Motor", "motor de tracțiune"),
    ("Crankcase Pressure", "presiune carter"),
    ("Internal Control Module", "unitate de comandă internă"),
    ("Pedestrian Alert Speaker", "difuzor avertizare pietoni"),
    ("Night Vision Camera", "cameră vedere nocturnă"),
    ("Interior Light Circuit", "circuit iluminare interioară"),
    ("Microphone Circuit", "circuit microfon"),
    ("Display Backlight Circuit", "circuit iluminare afișaj"),
    ("Encoder Motor", "motor codificator"),
    ("Restraints Deployed", "sisteme de reținere declanșate"),
    ("TCM Processor", "procesor TCM"),
    ("Multiple Gears Engaged", "mai multe trepte cuplate"),
    ("DPF Regeneration Duration", "durată regenerare DPF"),
    ("See Manufacturer", "consultați documentația producătorului"),
    ("Reserved - TBD", "rezervat - de stabilit"),
    ("Variant Selection", "selectare variantă"),
    ("Coolant Thermostat Below Regulating Temperature", "termostat lichid de răcire sub temperatura de reglare"),
    ("Coolant Thermostat", "termostat lichid de răcire"),
    ("O2 Sensor Circuit Range/Performance", "domeniu/performanță circuit senzor O2"),
    ("O2 Sensor Circuit High Voltage", "tensiune ridicată în circuitul senzorului O2"),
    ("O2 Sensor Circuit Low Voltage", "tensiune scăzută în circuitul senzorului O2"),
    ("O2 Sensor Circuit Malfunction", "defecțiune circuit senzor O2"),
    ("O2 Sensor Circuit Slow Response", "răspuns lent circuit senzor O2"),
    ("O2 Sensor Circuit No Activity Detected", "nicio activitate detectată în circuitul senzorului O2"),
    ("O2 Sensor Heater Circuit", "circuit încălzitor senzor O2"),
    ("O2 Sensor", "senzor O2"),
    ("Catalyst System Efficiency Below Threshold", "eficiența sistemului catalitic sub prag"),
    ("Random/Multiple Cylinder Misfire Detected", "rateuri de ardere aleatorii/multiple detectate"),
    ("High Speed CAN Communication Bus", "magistrală CAN de mare viteză"),
    ("Ambient Air Temperature Sensor", "senzor temperatură aer ambiant"),
    ("Battery Positive Contactor", "contactor pozitiv baterie"),
    ("Battery Negative Contactor", "contactor negativ baterie"),
    ("Camera Washer", "spălător cameră"),
    ("Air Assisted Injector Control", "comandă injector asistat cu aer"),
    ("Please Check DTC Memory", "verificați memoria DTC"),
    ("Brake Pad Replacement Mode", "mod înlocuire plăcuțe de frână"),
    ("Warm Up Catalyst", "încălzire catalizator"),
    ("Keep Alive Memory", "memorie menținută"),
    ("Second Fuel Pump", "a doua pompă de combustibil"),
    ("High Sides Shorted Together", "ramurile pe plus sunt scurtcircuitate împreună"),
    ("Does Not Match", "nu corespunde"),
    ("Data Mismatch", "neconcordanță date"),
    ("Thermal Shutdown", "oprire termică"),
    ("Child Seat", "scaun copil"),
    ("ABS Functions Temporarily Disabled", "funcțiile ABS sunt dezactivate temporar"),
    ("Yaw Rate Sensor", "senzor rată de girație"),
    ("Energy Management", "management energie"),
    ("Compact Disc", "disc compact"),
    ("Not Reached", "neatins"),
    ("Audible Warnings", "avertizări sonore"),
    ("Upstream Heated O2 Sensors Swapped", "senzorii O2 încălziți din amonte sunt inversați"),
    ("Inductive Signature Chip", "cip de identificare inductivă"),
    ("Dynamic Stability Control", "control dinamic al stabilității"),
    ("Control Module Not Coded", "unitate de comandă necodificată"),
    ("Read Only Memory", "memorie numai pentru citire"),
    ("Solar Radiation", "radiație solară"),
    ("Battery Saver", "economizor baterie"),
    ("Oil Change Reset Button", "buton resetare schimb ulei"),
    ("High Mount Stop Lamp", "lampă stop centrală"),
    ("Torque Converter", "convertizor de cuplu"),
    ("Rough Road", "drum denivelat"),
    ("One Touch", "o singură atingere"),
    ("Keyless Entry", "acces fără cheie"),
    ("Random Access Memory", "memorie cu acces aleatoriu"),
    ("Incorrect Gear Ratio", "raport de transmisie incorect"),
    ("Not Able To Complete", "nu poate finaliza"),
    ("Pedal Demand", "cerere pedală"),
    ("Not Programmed", "neprogramat"),
    ("Long Term Memory", "memorie pe termen lung"),
    ("Do Not Match", "nu corespund"),
    ("Acceptable Range", "domeniu acceptabil"),
    ("Counter Clockwise", "sens antiorar"),
    ("Tone Ring", "inel de impulsuri"),
    ("Ash Accumulation", "acumulare de cenușă"),
    ("Particulate Filter Restriction", "restricție filtru de particule"),
    ("Fuel Trim", "corecție combustibil"),
    ("Air Conditioner", "climatizare"),
    ("Longitudinal Acceleration", "accelerație longitudinală"),
    ("Four-Wheel Drive", "tracțiune integrală"),
    ("4-Wheel Drive", "tracțiune integrală"),
    ("Hazard Flash", "semnalizare de avarie"),
    ("Bulb Outage", "bec ars"),
    ("Not Received", "neprimit"),
    ("Early Activation", "activare prematură"),
    ("Short To GND Or VBATT", "scurtcircuit la masă sau la tensiunea bateriei"),
    ("High Side", "ramură pe plus"),
    ("Hard Fault Present", "defect permanent prezent"),
    ("Is Not Responding", "nu răspunde"),
    ("Cold Start", "pornire la rece"),
    ("Control Unit", "unitate de comandă"),
    ("Return Spring", "arc de revenire"),
    ("Power Sliding Door", "ușă culisantă electrică"),
    ("Contribution/Balance", "contribuție/echilibru"),
    ("Basic Setting / Configuration Issue", "problemă de setare de bază / configurație"),
    ("Glow Plug", "bujie incandescentă"),
    ("Non-Purge", "fără purjare"),
    ("Up/Down", "sus/jos"),
    ("Contact Plate", "placă de contact"),
    ("Interior Scanning", "monitorizare habitaclu"),
    ("Check DTC Memory", "verificare memorie DTC"),
    ("Cylinder Head", "chiulasă"),
    ("High Resolution", "rezoluție ridicată"),
    ("Lower Than Expected", "sub valoarea așteptată"),
    ("Positive Feed", "alimentare pozitivă"),
    ("Spark Test", "test aprindere"),
    ("High-Beam", "fază lungă"),
    ("Flash To Pass", "semnalizare cu farurile"),
    ("Seat Belt Buckle", "cataramă centură de siguranță"),
    ("Seatbelt", "centură de siguranță"),
    ("Out Of", "în afara"),
    ("Self Test", "autotest"),
    ("Long Coding Helper", "asistent codare extinsă"),
    ("Body Locking Probable Guidance", "ghidare orientativă pentru sistemul de închidere al caroseriei"),
    ("Diagnostic Procedures", "proceduri de diagnostic"),
    ("Common Procedures", "proceduri comune"),
    ("VCDS Function Index", "index funcții VCDS"),
    ("Airbag Coding", "codare airbag"),
    ("Coding Helper", "asistent codare"),
    ("Direct Coding", "codare directă"),
    ("ABS-Based Reset", "resetare bazată pe ABS"),
    ("Community Workflow", "procedură comunitară"),
    ("Gauge Test", "test indicatoare"),
    ("Cent. Elect.", "electronică centrală"),
    ("Central Conv.", "confort centralizat"),
    ("Acc/Start Auth.", "autorizare acces/pornire"),
    ("Door Elect.", "electronică ușă"),
    ("Instruments", "panou instrumente"),
    ("Advanced Measuring Values", "valori de măsură avansate"),
    ("Adv. Meas. Values", "valori de măsură avansate"),
    ("Requested/Actual", "solicitat/real"),
    ("Target/Actual", "țintă/real"),
    ("Actual/Specified", "real/specificat"),
    ("Live Data", "date actuale"),
    ("Clear DTC", "șterge DTC"),
    ("License Plate", "număr de înmatriculare"),
    ("Lambda Probe Heater Activation", "activare încălzitor sondă lambda"),
    ("Actual Air Mass", "masă reală de aer"),
    ("Aer Mass", "masă de aer"),
    ("Air Mass", "masă de aer"),
    ("Heater Activation", "activare încălzitor"),
    ("Cheia 1 - limita inferioară depășită", "cheia 1 - valoare sub limita inferioară"),
    ("Management energie activ", "managementul energiei este activ"),
    ("Capac rezervor - blocare", "clapetă rezervor combustibil - blocare"),
    ("Capac rezervor - deblocare", "clapetă rezervor combustibil - deblocare"),
    ("Open/Close Rear Parking Brake", "deschidere/închidere frână de parcare spate"),
    ("Open Rear Parking Brake", "deschidere frână de parcare spate"),
    ("Close Rear Parking Brake", "închidere frână de parcare spate"),
    ("Long Coding Helper", "asistent codare extinsă"),
    ("Long Adaptation", "adaptare extinsă"),
    ("Installation List", "listă de instalare"),
    ("Brake Electronics", "electronică frâne"),
    ("Engine Electronics", "electronică motor"),
    ("Central Electronics", "electronică centrală"),
    ("Battery Regulation", "reglare baterie"),
    ("Comfort System", "sistem confort"),
    ("Checking Throttle Valve Adaptation", "verificare adaptare clapetă de accelerație"),
    ("Throttle Body Alignment", "aliniere corp clapetă de accelerație"),
    ("Throttle Valve Adaptation", "adaptare clapetă de accelerație"),
    ("Seat Occupied Recognition", "recunoaștere ocupare scaun"),
    ("Passenger Occupancy", "ocupare scaun pasager"),
    ("Function Test", "test funcțional"),
    ("Test Drive", "test rutier"),
    ("Safe Workflow", "flux de lucru sigur"),
    ("Factory Mode", "mod fabrică"),
    ("Auto-Lock", "blocare automată"),
    ("Auto-Unlock", "deblocare automată"),
    ("Selective Locking", "închidere selectivă"),
    ("Needle Sweep / Staging", "test ace indicatoare"),
    ("Staging / Needle Sweep", "test ace indicatoare"),
    ("Needle Sweep", "test ace indicatoare"),
    ("Lap Timer", "cronometru tur"),
    ("Coming Home / Leaving Home", "iluminare la sosire / plecare"),
    ("Rain Closing", "închidere geamuri la ploaie"),
    ("Cornering", "iluminare în viraj"),
    ("Emergency Regeneration", "regenerare de urgență"),
    ("Measuring Values", "valori de măsură"),
    ("Main Screen", "ecran principal"),
    ("Instrument Cluster", "panou instrumente"),
    ("Controller Replacement", "înlocuire unitate de comandă"),
    ("Component Identification", "identificare componentă"),
    ("Key Personalization", "personalizare cheie"),
    ("Limit Stops", "capete de cursă"),
    ("Insufficient Coolant Temperature for Closed Loop Fuel Control", "temperatură insuficientă a lichidului de răcire pentru reglarea combustibilului în buclă închisă"),
    ("Closed Loop Fuel Control", "reglare combustibil în buclă închisă"),
    ("Transmission Control Module", "unitate de comandă transmisie"),
    ("Engine Control Module", "unitate de comandă motor"),
    ("Body Control Module", "unitate de comandă caroserie"),
    ("No Communication / DTC Stored", "fără comunicație / DTC memorat"),
    ("No Communication", "fără comunicație"),
    ("DTC Stored", "DTC memorat"),
    ("Out of Range", "în afara domeniului"),
    ("Below Threshold", "sub prag"),
    ("Above Threshold", "peste prag"),
    ("Slow Response", "răspuns lent"),
    ("No Activity Detected", "nicio activitate detectată"),
    ("Stuck On", "blocat în stare activă"),
    ("Stuck Off", "blocat în stare inactivă"),
    ("Transfer Case", "cutie de transfer"),
    ("Shock Absorber", "amortizor"),
    ("Seat Position", "poziție scaun"),
    ("Seat Height", "înălțime scaun"),
    ("Seat Back", "spătar scaun"),
    ("Passenger Seat", "scaun pasager"),
    ("Driver Seat", "scaun șofer"),
    ("Windshield", "parbriz"),
    ("Ignition Coil", "bobină de aprindere"),
    ("Ignition Switch", "contact pornire"),
    ("Idle Speed", "turație ralanti"),
    ("Control Circuit", "circuit de comandă"),
    ("Reference Voltage", "tensiune de referință"),
    ("System Performance", "performanță sistem"),
    ("Incorrect Ratio", "raport incorect"),
    ("Excessive Time", "timp excesiv"),
    ("Stable Operation", "funcționare stabilă"),
    ("Lack of", "lipsă"),
    ("Normed Load Value", "sarcină normalizată"),
    ("Ambient Air Pressure", "presiune aer ambiant"),
    ("Unlearning Counter According OBD", "contor de reînvățare conform OBD"),
    ("Crankshaft Speed (RPM)", "turație arbore cotit (RPM)"),
    ("Lambda Probe Heater Activation", "activare încălzitor sondă lambda"),
    ("Actual Air Mass", "masă reală de aer"),
    ("Lambda Signal", "semnal sondă lambda"),
    ("Lambda Probe Diagnosis-Bits", "biți diagnoză sondă lambda"),
    ("Lambda Probe Temperature Signal", "semnal temperatură sondă lambda"),
    ("Readiness Bits", "biți stare emisii"),
    ("Contextual Guidance", "ghidare contextuală"),
    ("Thursday", "Joi"),
    ("Wednesday", "Miercuri"),
    ("Tuesday", "Marți"),
    ("Monday", "Luni"),
    ("Friday", "Vineri"),
    ("Saturday", "Sâmbătă"),
    ("Sunday", "Duminică"),
    ("January", "Ianuarie"),
    ("February", "Februarie"),
    ("March", "Martie"),
    ("April", "Aprilie"),
    ("May", "Mai"),
    ("June", "Iunie"),
    ("July", "Iulie"),
    ("August", "August"),
    ("September", "Septembrie"),
    ("October", "Octombrie"),
    ("November", "Noiembrie"),
    ("December", "Decembrie"),
    ("Replacement/Calibration Chain", "lanț de înlocuire și calibrare"),
    ("Replacement and Calibration", "înlocuire și calibrare"),
    ("Electrical Fault", "defecțiune electrică"),
    ("Electrical Malfunction", "funcționare electrică defectuoasă"),
    ("Open or Short to Ground", "circuit întrerupt sau scurtcircuit la masă"),
    ("Open or Short to Plus", "circuit întrerupt sau scurtcircuit la plus"),
    ("Lower Limit Exceeded", "valoare sub limita inferioară"),
    ("Upper Limit Exceeded", "valoare peste limita superioară"),
    ("Component Protection Active", "protecția componentelor este activă"),
    ("Energy Management Active", "managementul energiei este activ"),
    ("Locking Unit for Central Locking", "unitate de blocare pentru închiderea centralizată"),
    ("Motor for Central Locking", "motor pentru închiderea centralizată"),
    ("Fuel Tank Cap", "clapetă rezervor combustibil"),
    ("Coolant Pump", "pompă lichid de răcire"),
    ("Databus Missing Message", "mesaj lipsă pe magistrala de date"),
    ("Data Bus", "magistrală de date"),
    ("Mass Air Flow", "debit masic de aer"),
    ("Mass or Volume Air Flow", "debit masic sau volumic de aer"),
    ("Manifold Absolute Pressure/Barometric Pressure", "presiune absolută galerie/presiune barometrică"),
    ("Throttle/Pedal Position Sensor/Switch", "senzor/comutator poziție clapetă/pedală"),
    ("Throttle Position Sensor/Switch", "senzor/comutator poziție clapetă"),
    ("Heated Oxygen Sensor", "senzor de oxigen încălzit"),
    ("Oxygen Sensor", "senzor de oxigen"),
    ("Fuel Rail/System Pressure", "presiune rampă/sistem combustibil"),
    ("Exhaust Gas Recirculation", "recirculare gaze de eșapament"),
    ("Evaporative Emission Control System", "sistem control emisii evaporative"),
    ("Evaporative Emission System", "sistem emisii evaporative"),
    ("Intake Manifold Runner Control", "comandă clapete galerie admisie"),
    ("Turbocharger/Supercharger", "turbocompresor/compresor"),
    ("Turbo/Super Charger", "turbocompresor/compresor"),
    ("Crankshaft Position", "poziție arbore cotit"),
    ("Camshaft Position", "poziție arbore cu came"),
    ("Transmission Fluid Pressure", "presiune ulei transmisie"),
    ("Transmission Fluid Temperature", "temperatură ulei transmisie"),
    ("Transmission Range Sensor", "senzor gamă transmisie"),
    ("Torque Converter Clutch", "ambreiaj convertizor de cuplu"),
    ("Shift Solenoid", "electrovalvă schimbare treaptă"),
    ("Pressure Control Solenoid", "electrovalvă reglare presiune"),
    ("Lost Communication With", "comunicație pierdută cu"),
    ("Invalid Data Received From", "date nevalide primite de la"),
    ("Control Module", "unitate de comandă"),
    ("Controller Area Network", "rețea CAN"),
    ("Serial Communication", "comunicație serială"),
    ("Circuit Range/Performance Problem", "domeniu/performanță necorespunzătoare a circuitului"),
    ("Circuit Range/Performance", "domeniu/performanță necorespunzătoare a circuitului"),
    ("Circuit Intermittent", "circuit intermitent"),
    ("Circuit Malfunction", "defecțiune a circuitului"),
    ("Circuit High Input", "semnal ridicat al circuitului"),
    ("Circuit Low Input", "semnal scăzut al circuitului"),
    ("Circuit High", "nivel ridicat al circuitului"),
    ("Circuit Low", "nivel scăzut al circuitului"),
    ("Circuit/Open", "circuit întrerupt"),
    ("Circuit / Open", "circuit întrerupt"),
    ("Circuit Open", "circuit întrerupt"),
    ("Open Circuit", "circuit întrerupt"),
    ("Short to Battery", "scurtcircuit la plusul bateriei"),
    ("Short To Battery", "scurtcircuit la plusul bateriei"),
    ("Short to Ground", "scurtcircuit la masă"),
    ("Short To Ground", "scurtcircuit la masă"),
    ("Short to Plus", "scurtcircuit la plus"),
    ("No Signal/Communication", "fără semnal/comunicație"),
    ("No Signal", "fără semnal"),
    ("Implausible Signal", "semnal neplauzibil"),
    ("Signal too High", "semnal prea ridicat"),
    ("Signal too Low", "semnal prea scăzut"),
    ("Performance or Incorrect Operation", "performanță sau funcționare incorectă"),
    ("Incorrect Correlation", "corelație incorectă"),
    ("Correlation", "corelație"),
    ("Insufficient Flow", "debit insuficient"),
    ("System Too Lean", "amestec prea sărac"),
    ("System Too Rich", "amestec prea bogat"),
    ("Random/Multiple Cylinder Misfire", "rateuri aleatorii/multiple de ardere"),
    ("Cylinder Misfire Detected", "rateu de ardere detectat la cilindru"),
    ("Glow Plug Circuit", "circuit bujie incandescentă"),
    ("Fuel Injector", "injector combustibil"),
    ("Fuel Pump", "pompă combustibil"),
    ("Fuel Pressure", "presiune combustibil"),
    ("Engine Coolant Temperature", "temperatură lichid de răcire motor"),
    ("Intake Air Temperature", "temperatură aer admisie"),
    ("Vehicle Speed Sensor", "senzor viteză vehicul"),
    ("Idle Air Control", "control aer la ralanti"),
    ("Catalyst System Efficiency Below Threshold", "eficiență catalizator sub prag"),
    ("Particulate Filter", "filtru de particule"),
    ("System Voltage", "tensiune sistem"),
    ("Power Supply", "alimentare electrică"),
    ("Parking Brake", "frână de parcare"),
    ("Steering Angle Sensor", "senzor unghi volan"),
    ("Steering Assist", "servodirecție"),
    ("Anti-Lock Brake", "sistem antiblocare frâne"),
    ("Wheel Speed Sensor", "senzor viteză roată"),
    ("Air Bag", "airbag"),
    ("Seat Belt", "centură de siguranță"),
    ("Passenger Compartment", "habitaclu"),
    ("Door Ajar", "ușă deschisă"),
    ("Central Locking", "închidere centralizată"),
    ("Headlamp", "far"),
    ("Headlight", "far"),
    ("Daytime Running Lamp", "lumină de zi"),
    ("License Lamp", "lampă număr înmatriculare"),
    ("Windshield Wiper", "ștergător parbriz"),
    ("Windshield Washer", "spălător parbriz"),
    ("Air Conditioning", "climatizare"),
    ("Basic Settings", "Setări de bază"),
    ("Basic Setting", "Setare de bază"),
    ("Fault Codes", "Coduri de eroare"),
    ("Measuring Blocks", "Blocuri de măsură"),
    ("Advanced Measuring Values", "Valori de măsură avansate"),
    ("Output Tests", "Teste actuatori"),
    ("Security Access", "Acces securizat"),
    ("Long Coding", "Codare extinsă"),
    ("Coding", "Codare"),
    ("Adaptation", "Adaptare"),
    ("Readiness", "Stare disponibilitate emisii"),
    ("Auto-Scan", "Scanare automată"),
    ("Service Reminder Interval", "interval de service"),
    ("Data Logging", "înregistrare date"),
    ("Controller Identification", "identificare unitate de comandă"),
)

_WORDS: tuple[tuple[str, str], ...] = (
    ("hybrid", "hibrid"), ("reductant", "agent reducător"),
    ("pack", "pachet"), ("alternative", "alternativ"),
    ("charger", "încărcător"), ("cooler", "răcitor"),
    ("inverter", "invertor"), ("camshaft", "arbore cu came"),
    ("crankshaft", "arbore cotit"), ("deactivation", "dezactivare"),
    ("deployment", "declanșare"), ("learning", "învățare"),
    ("incompatibility", "incompatibilitate"), ("profile", "profil"),
    ("cell", "celulă"), ("interface", "interfață"),
    ("offset", "abatere"), ("negative", "negativ"),
    ("balancing", "echilibrare"), ("fork", "furcă"),
    ("grille", "grilă"), ("shutter", "obturator"),
    ("coupler", "cuplaj"), ("restraints", "sisteme de reținere"),
    ("restraint", "sistem de reținere"), ("aftertreatment", "post-tratare"),
    ("rocker", "culbutor"), ("arm", "braț"),
    ("learned", "învățat"), ("lever", "levier"),
    ("disconnect", "deconectare"), ("imbalance", "dezechilibru"),
    ("friction", "frecare"), ("overspeed", "supraturație"),
    ("underspeed", "subturație"), ("row", "rând"),
    ("pumping", "pompare"), ("combustion", "ardere"),
    ("pulse", "impuls"), ("forced", "forțat"),
    ("min", "minim"), ("shutoff", "oprire"),
    ("processing", "procesare"), ("image", "imagine"),
    ("incompatible", "incompatibil"), ("regeneration", "regenerare"),
    ("particulate", "particule"), ("matter", "materie"),
    ("stage", "etaj"), ("fill", "umplere"),
    ("crankcase", "carter"), ("intermediate", "intermediar"),
    ("variation", "variație"), ("tuning", "reglaj"),
    ("vibration", "vibrație"), ("processor", "procesor"),
    ("effort", "efort"), ("heat", "căldură"),
    ("exchanger", "schimbător"), ("deterioration", "deteriorare"),
    ("precharge", "preîncărcare"), ("runner", "canal"),
    ("isolation", "izolație"), ("third", "terț"),
    ("quantity", "cantitate"), ("quality", "calitate"),
    ("vaporizer", "vaporizator"), ("hydrogen", "hidrogen"),
    ("overtemperature", "supraîncălzire"), ("pawl", "clichet"),
    ("distribution", "distribuție"), ("belt", "curea"),
    ("classification", "clasificare"), ("restricted", "restricționat"),
    ("response", "răspuns"), ("delayed", "întârziat"),
    ("ventilation", "ventilație"), ("wake", "activare"),
    ("reservoir", "rezervor"), ("adjustment", "reglaj"),
    ("assist", "asistență"), ("monitoring", "monitorizare"),
    ("engage", "cuplare"), ("limits", "limite"),
    ("long", "lung"), ("axis", "axă"),
    ("illumination", "iluminare"), ("vapor", "vapori"),
    ("retarded", "întârziat"), ("advanced", "avansat"),
    ("biased", "deviat"), ("leaking", "cu scurgeri"),
    ("cap", "capac"), ("distance", "distanță"),
    ("four", "patru"), ("compression", "compresie"),
    ("engagement", "cuplare"), ("limited", "limitat"),
    ("enter", "intrare"), ("inhibit", "inhibare"),
    ("ozone", "ozon"), ("disengagement", "decuplare"),
    ("driving", "conducere"), ("apply", "acționare"),
    ("thermostat", "termostat"), ("upshift", "schimbare în treaptă superioară"),
    ("proximity", "proximitate"), ("sound", "sunet"),
    ("selection", "selectare"), ("medium", "mediu"),
    ("anode", "anod"), ("curtain", "cortină"),
    ("discharge", "descărcare"), ("frequency", "frecvență"),
    ("excitation", "excitație"), ("lift", "ridicare"),
    ("inflatable", "gonflabil"), ("alert", "avertizare"),
    ("measurement", "măsurare"), ("minimum", "minim"),
    ("unstable", "instabil"), ("slip", "patinare"),
    ("thickness", "grosime"), ("automated", "automatizat"),
    ("obstacle", "obstacol"), ("purpose", "scop"),
    ("indicated", "indicat"), ("installed", "instalat"),
    ("engaged", "cuplat"), ("trailer", "remorcă"),
    ("activity", "activitate"), ("hose", "furtun"),
    ("deteriorated", "deteriorat"), ("fuse", "siguranță fuzibilă"),
    ("adsorber", "canistră cu carbon activ"), ("deceleration", "decelerare"),
    ("exceedence", "depășire"), ("stabilization", "stabilizare"),
    ("gateway", "poartă de comunicație"), ("entertainment", "multimedia"),
    ("knee", "genunchi"), ("pedestrian", "pieton"),
    ("evaporator", "vaporizator"), ("amplifier", "amplificator"),
    ("driveline", "linie de transmisie"), ("swapped", "inversat"),
    ("signals", "semnale"), ("humidity", "umiditate"),
    ("filter", "filtru"), ("mount", "suport"),
    ("leakage", "scurgere"), ("accumulation", "acumulare"),
    ("sample", "eșantion"), ("reagent", "reactiv"),
    ("parking", "parcare"), ("convenience", "confort"),
    ("controls", "comenzi"), ("drain", "drenaj"),
    ("sunroof", "trapă"), ("blending", "amestec"),
    ("large", "mare"), ("refueling", "realimentare"),
    ("connection", "conexiune"), ("economy", "economie"),
    ("skip", "sărire"), ("downshift", "retrogradare"),
    ("consumption", "consum"), ("slow", "lent"),
    ("sensing", "detectare"), ("unrequested", "nesolicitat"),
    ("movement", "mișcare"), ("interstage", "interetaj"),
    ("object", "obiect"), ("information", "informații"),
    ("roof", "plafon"), ("player", "unitate de redare"),
    ("cathode", "catod"), ("tension", "tensiune"),
    ("sun", "solar"), ("travel", "cursă"),
    ("delivered", "furnizat"), ("valves", "supape"),
    ("damping", "amortizare"), ("roll", "ruliu"),
    ("assisted", "asistat"), ("state", "stare"),
    ("very", "foarte"), ("accelerator", "accelerație"),
    ("accumulator", "acumulator"), ("step", "pas"),
    ("achieve", "atingere"), ("fast", "rapid"),
    ("presence", "prezență"), ("sequence", "secvență"),
    ("leveling", "nivelare"), ("moveable", "deplasabil"),
    ("wireless", "fără fir"), ("maintenance", "întreținere"),
    ("entrapment", "anti-strivire"), ("board", "placă"),
    ("running", "funcționare"), ("aerodynamic", "aerodinamic"),
    ("feature", "funcție"), ("changer", "schimbător"),
    ("stack", "ansamblu"), ("night", "noapte"),
    ("vision", "vedere"), ("mix", "amestec"),
    ("back", "spate"), ("dynamics", "dinamică"),
    ("force", "forță"), ("chamber", "cameră"),
    ("cranking", "antrenare la pornire"), ("overboost", "suprapresiune"),
    ("underboost", "presiune insuficientă"), ("disconnected", "deconectat"),
    ("fresh", "proaspăt"), ("immobiliser", "imobilizator"),
    ("slippage", "patinare"), ("planetary", "planetar"),
    ("incomplete", "incomplet"), ("event", "eveniment"),
    ("recorder", "înregistrator"), ("additive", "aditiv"),
    ("cleaner", "curățare"), ("degassing", "degazare"),
    ("unexpected", "neașteptat"), ("dry", "uscat"),
    ("tensioner", "întinzător"), ("personal", "personal"),
    ("actuation", "acționare"), ("thermal", "termic"),
    ("security", "securitate"), ("authentication", "autentificare"),
    ("header", "antet"), ("mixing", "amestecare"),
    ("outside", "exterior"), ("rollover", "răsturnare"),
    ("limiter", "limitator"), ("adjust", "reglare"),
    ("thorax", "torace"), ("pelvic", "pelvian"),
    ("speaker", "difuzor"), ("light", "lumină"),
    ("encoder", "codificator"), ("hill", "pantă"),
    ("required", "necesar"), ("separation", "separare"),
    ("stabilisation", "stabilizare"), ("blocked", "blocat"),
    ("delivery", "livrare"), ("propulsion", "propulsie"),
    ("synchronization", "sincronizare"), ("few", "prea puține"),
    ("orifice", "orificiu"), ("cancel", "anulare"),
    ("de-energized", "dezactivat"), ("checksum", "sumă de control"),
    ("replace", "înlocuire"), ("conversion", "conversie"),
    ("discharging", "descărcare"), ("fired", "declanșat"),
    ("blockage", "blocaj"), ("sudden", "brusc"),
    ("substrate", "substrat"), ("adsorption", "adsorbție"),
    ("duration", "durată"), ("conditions", "condiții"),
    ("number", "număr"), ("feedgas", "gaz de alimentare"),
    ("empty", "gol"), ("terrain", "teren"),
    ("personalization", "personalizare"), ("compass", "busolă"),
    ("positioning", "poziționare"), ("liftgate", "hayon"),
    ("television", "televizor"), ("computer", "calculator"),
    ("telematic", "telematică"), ("tachograph", "tahograf"),
    ("folding", "pliere"), ("top", "plafon"),
    ("recall", "rechemare"), ("transceiver", "emițător-receptor"),
    ("speech", "vorbire"), ("recognition", "recunoaștere"),
    ("haptic", "tactil"), ("device", "dispozitiv"),
    ("integration", "integrare"), ("mapping", "cartografiere"),
    ("localization", "localizare"), ("improper", "incorect"),
    ("certificate", "certificat"), ("expander", "extensor"),
    ("backpressure", "contrapresiune"), ("multifunction", "multifuncțional"),
    ("bolster", "suport lateral"), ("folder", "mecanism de pliere"),
    ("defroster", "dezaburire"), ("marker", "gabarit"),
    ("trunk", "portbagaj"), ("lid", "capac"),
    ("microphone", "microfon"), ("backlight", "iluminare fundal"),
    ("rotation", "rotație"), ("lining", "garnitură"),
    ("wear", "uzură"), ("longitude", "longitudine"),
    ("diameter", "diametru"), ("excessively", "excesiv"),
    ("modulation", "modulație"), ("bias", "decalaj"),
    ("coupling", "cuplare"), ("cut", "întrerupere"),
    ("half", "jumătate"), ("connector", "conector"),
    ("initiator", "inițiator"), ("regulating", "reglare"),
    ("frequent", "frecvent"), ("relapsed", "reapărut"),
    ("startup", "pornire"), ("revolutions", "rotații"),
    ("producing", "producere"), ("fueling", "alimentare combustibil"),
    ("loose", "slăbit"), ("rationality", "plauzibilitate"),
    ("rough", "neregulat"), ("resume", "reluare"),
    ("deployed", "declanșat"), ("sum", "sumă"),
    ("options", "opțiuni"), ("calculation", "calcul"),
    ("odometer", "odometru"), ("unauthorized", "neautorizat"),
    ("hot", "fierbinte"), ("late", "întârziat"),
    ("restart", "repornire"), ("anticipate", "anticipare"),
    ("push", "apăsare"), ("gears", "trepte"),
    ("slipping", "patinare"), ("period", "perioadă"),
    ("cycling", "ciclu"), ("plug", "ștecher"),
    ("cord", "cablu"), ("date", "dată"),
    ("learn", "învățare"), ("exceeding", "depășire"),
    ("crank", "antrenare"), ("reserved", "rezervat"),
    ("airflow", "debit aer"), ("wait", "așteptare"),
    ("inducement", "restricție de funcționare"), ("canister", "canistră"),
    ("unmetered", "nemăsurat"), ("stabilizer", "stabilizator"),
    ("alignment", "aliniere"), ("exceedance", "depășire"),
    ("interruption", "întrerupere"), ("dosing", "dozare"),
    ("sulfur", "sulf"), ("insulation", "izolație"),
    ("cabin", "habitaclu"), ("tuner", "selector radio"),
    ("mobile", "mobil"), ("hands-free", "mâini libere"),
    ("emissions", "emisii"), ("critical", "critic"),
    ("assistance", "asistență"), ("subscription", "abonament"),
    ("telephone", "telefon"), ("expansion", "extensie"),
    ("cutoff", "întrerupere"), ("retained", "menținut"),
    ("clock", "ceas"),
    ("supercharger", "compresor mecanic"), ("display", "afișaj"),
    ("multi", "multiplu"), ("dam", "deflector"),
    ("set", "setare"), ("lost", "pierdut"),
    ("gas", "gaz"), ("head", "cap"),
    ("bank", "banc"), ("block", "bloc"),
    ("hub", "concentrator"), ("satellite", "satelit"),
    ("electrical", "electric"), ("electronic", "electronic"),
    ("replacement", "înlocuire"), ("calibration", "calibrare"),
    ("protection", "protecție"), ("management", "management"),
    ("active", "activ"), ("inactive", "inactiv"),
    ("exceeded", "depășit"), ("limit", "limită"),
    ("rich", "bogat"), ("lean", "sărac"),
    ("message", "mesaj"), ("reference", "referință"),
    ("plausibility", "plauzibilitate"), ("operation", "funcționare"),
    ("for", "pentru"), ("with", "cu"), ("without", "fără"),
    ("from", "de la"), ("into", "în"), ("between", "între"),
    ("during", "în timpul"), ("before", "înainte"), ("after", "după"),
    ("above", "peste"), ("below", "sub"), ("under", "sub"),
    ("over", "peste"), ("through", "prin"), ("and", "și"),
    ("not", "nu"), ("too", "prea"), ("seat", "scaun"),
    ("passenger", "pasager"), ("wiper", "ștergător"),
    ("ignition", "aprindere/contact"), ("potentiometer", "potențiometru"),
    ("throttle", "clapetă accelerație"), ("traction", "tracțiune"),
    ("error", "eroare"), ("height", "înălțime"),
    ("shift", "schimbare treaptă"), ("auxiliary", "auxiliar"),
    ("lock", "blocare"), ("fan", "ventilator"),
    ("forward", "înainte"), ("rearward", "înapoi"),
    ("servo", "servomotor"), ("pedal", "pedală"),
    ("assembly", "ansamblu"), ("horizontal", "orizontal"),
    ("vertical", "vertical"), ("self", "auto"),
    ("crash", "impact"), ("climate", "climatizare"),
    ("turn", "viraj"), ("evaporative", "evaporativ"),
    ("injection", "injecție"), ("recline", "înclinare spătar"),
    ("gear", "treaptă"), ("delay", "întârziere"),
    ("damper", "amortizor/clapetă"), ("inlet", "intrare"),
    ("outlet", "ieșire"), ("failed", "defect"),
    ("metering", "dozare"), ("hydraulic", "hidraulic"),
    ("accelerometer", "accelerometru"), ("monitor", "monitorizare"),
    ("catalyst", "catalizator"), ("misfire", "rateu de ardere"),
    ("center", "central"), ("column", "coloană"),
    ("cruise", "pilot automat"), ("washer", "spălător"),
    ("mode", "mod"), ("select", "selectare"),
    ("audio", "audio"), ("park", "parcare"),
    ("side", "latură"), ("down", "jos"),
    ("pompa", "pompă"), ("racire", "răcire"),
    ("verifica", "verifică"), ("masoara", "măsoară"),
    ("key", "cheie"), ("body", "caroserie"),
    ("locking", "blocare"), ("unlock", "deblocare"),
    ("probable", "probabil"), ("guidance", "ghidare"),
    ("legacy", "generație veche"), ("electronics", "electronică"),
    ("safe", "sigur"), ("workflow", "flux de lucru"),
    ("controller", "unitate de comandă"), ("helper", "asistent"),
    ("field", "câmp"), ("group", "grup"),
    ("backup", "copie de siguranță"), ("factory", "fabrică"),
    ("confirmations", "confirmări"), ("comfort", "confort"),
    ("doors", "uși"), ("integrated", "integrat"),
    ("instrument", "instrument"), ("cluster", "panou instrumente"),
    ("matching", "asociere"), ("limitation", "limitare"),
    ("identification", "identificare"), ("lighting", "iluminare"),
    ("staging", "test ace indicatoare"), ("timer", "cronometru"),
    ("route", "traseu"), ("based", "bazat"),
    ("reset", "resetare"), ("channel", "canal"),
    ("selective", "selectiv"), ("community", "comunitar"),
    ("subsystem", "subsistem"), ("baseline", "verificare de bază"),
    ("occupancy", "ocupare scaun"), ("regulation", "reglare"),
    ("channels", "canale"), ("function", "funcție"),
    ("emergency", "urgență"), ("brakes", "frâne"),
    ("main", "principal"), ("screen", "ecran"),
    ("soot", "funingine"), ("load", "încărcare"),
    ("temperatures", "temperaturi"), ("values", "valori"),
    ("live", "actuale"), ("rain", "ploaie"),
    ("closing", "închidere"), ("opening", "deschidere"),
    ("then", "apoi"), ("via", "prin"),
    ("software", "software"), ("exact", "exact"),
    ("activation", "activare"), ("wideband", "cu bandă largă"),
    ("requested", "solicitat"), ("specified", "specificat"),
    ("target", "țintă"), ("actual", "real"),
    ("stroke", "cursă"), ("license", "înmatriculare"),
    ("probe", "sondă"), ("spec", "specificat"),
    ("angle", "unghi"), ("index", "indice"),
    ("airbags", "airbag"), ("gauge", "indicator"),
    ("direct", "direct"), ("if", "dacă"),
    ("immobilizer", "imobilizator"),
    ("si", "și"), ("usa", "ușă"), ("usi", "uși"),
    ("inlocuit", "înlocuit"), ("inlocuire", "înlocuire"),
    ("daca", "dacă"), ("exista", "există"),
    ("confirmari", "confirmări"), ("incarcare", "încărcare"),
    ("conditionata", "condiționată"), ("dupa", "după"),
    ("masurare", "măsurare"), ("directie", "direcție"),
    ("frana", "frână"), ("temperatura", "temperatură"),
    ("transfer", "transfer"), ("aux", "auxiliar"),
    ("out", "în afara"), ("drive", "acționare"),
    ("shock", "amortizor"), ("cam", "camă"),
    ("autolamp", "lumini automate"), ("run", "funcționare"),
    ("boost", "supraalimentare"), ("fluid", "lichid"),
    ("shorted", "scurtcircuitat"), ("heated", "încălzit"),
    ("disable", "dezactivare"), ("spring", "arc"),
    ("ride", "rulare"), ("differential", "diferențial"),
    ("turbocharger", "turbocompresor"), ("vent", "aerisire"),
    ("theft", "antifurt"), ("beam", "fascicul"),
    ("ckt", "circuit"), ("responding", "răspunde"),
    ("start", "pornire"), ("rotor", "rotor"),
    ("purge", "purjare"), ("off", "oprit"),
    ("return", "revenire"), ("sense", "detectare"),
    ("codes", "coduri"), ("unit", "unitate"),
    ("entry", "acces"), ("backward", "înapoi"),
    ("inflator", "generator gaz airbag"),
    ("contribution", "contribuție"), ("balance", "echilibru"),
    ("configuration", "configurație"), ("panel", "panou"),
    ("wastegate", "supapă descărcare turbo"),
    ("reverse", "marșarier"), ("non", "fără"),
    ("neutral", "neutru"), ("decklid", "capac portbagaj"),
    ("handle", "mâner"), ("stalled", "blocat"),
    ("sliding", "culisant"), ("broken", "întrerupt"),
    ("compressor", "compresor"), ("disarm", "dezarmare"),
    ("remote", "telecomandă"), ("interior", "interior"),
    ("loop", "buclă"), ("check", "verificare"),
    ("condition", "condiție"), ("petal", "pedală"),
    ("knock", "detonație"), ("resolution", "rezoluție"),
    ("idle", "ralanti"), ("expected", "așteptat"),
    ("feed", "alimentare"), ("temp", "temperatură"),
    ("increase", "creștere"), ("decrease", "scădere"),
    ("variable", "variabil"), ("interactive", "interactiv"),
    ("plate", "placă"), ("dim", "reglare intensitate"),
    ("airintake", "admisie aer"), ("pretensioner", "pretensionator"),
    ("resistance", "rezistență"), ("corner", "viraj"),
    ("efficiency", "eficiență"), ("powertrain", "grup motopropulsor"),
    ("related", "asociat"), ("single", "unic"),
    ("closed", "închis"), ("refrigerant", "agent frigorific"),
    ("indicates", "indică"), ("unable", "imposibil"),
    ("change", "schimbare"), ("mechanical", "mecanic"),
    ("timeout", "timp expirat"), ("pulses", "impulsuri"),
    ("switching", "comutare"), ("than", "decât"),
    ("link", "legătură"), ("torque", "cuplu"),
    ("time", "timp"), ("code", "cod"),
    ("safety", "siguranță"), ("clockwise", "sens orar"),
    ("backlite", "lunetă"), ("illuminated", "iluminat"),
    ("occupied", "ocupat"), ("common", "comun"),
    ("buckle", "cataramă"), ("drivers", "șofer"),
    ("manifold", "galerie"), ("insufficient", "insuficient"),
    ("rail", "rampă"), ("cooling", "răcire"),
    ("overcurrent", "supracurent"), ("overtemp", "supraîncălzire"),
    ("overadvanced", "avansat excesiv"),
    ("present", "prezent"), ("first", "prima"),
    ("many", "multe"), ("only", "doar"),
    ("the", ""), ("of", "al"), ("to", "la"),
    ("or", "sau"), ("is", "este"), ("on", "activ"),
    ("in", "în"), ("up", "sus"), ("no", "fără"),
    ("sensors", "senzori"), ("tank", "rezervor"),
    ("signature", "semnătură"), ("inductive", "inductiv"),
    ("horn", "claxon"), ("defrost", "dezaburire"),
    ("chime", "avertizor sonor"), ("master", "principal"),
    ("dome", "plafonieră"), ("hazard", "avarie"),
    ("tone", "ton"), ("detection", "detectare"),
    ("outage", "întrerupere"), ("applied", "acționat"),
    ("close", "închidere"), ("coherency", "coerență"),
    ("stability", "stabilitate"), ("acknowledgment", "confirmare"),
    ("databus", "magistrală de date"), ("chassis", "șasiu"),
    ("network", "rețea"), ("read", "citire"),
    ("sensed", "detectat"), ("early", "prematur"),
    ("command", "comandă"), ("received", "primit"),
    ("counter", "contor"), ("radiation", "radiație"),
    ("saver", "economizor"), ("button", "buton"),
    ("release", "eliberare"), ("flash", "semnalizare"),
    ("tail", "spate"), ("antenna", "antenă"),
    ("post", "după"), ("positive", "pozitiv"),
    ("tape", "casetă"), ("faulted", "defect"),
    ("stop", "stop"), ("dynamic", "dinamic"),
    ("status", "stare"), ("converter", "convertizor"),
    ("but", "dar"), ("adaptive", "adaptiv"),
    ("water", "apă"), ("line", "linie"),
    ("hold", "menținere"), ("rate", "rată"),
    ("bypass", "ocolire"), ("available", "disponibil"),
    ("override", "suprascriere"), ("reduction", "reducere"),
    ("foot", "picioare"), ("coolair", "aer rece"),
    ("accessory", "accesorii"), ("one", "unu"),
    ("touch", "atingere"), ("keyless", "fără cheie"),
    ("phone", "telefon"), ("handset", "receptor"),
    ("squib", "capsă pirotehnică"), ("headrest", "tetieră"),
    ("reach", "adâncime"), ("tilt", "înclinare"),
    ("tooth", "dinte"), ("ring", "inel"),
    ("max", "maxim"), ("defective", "defect"),
    ("restriction", "restricție"), ("trim", "corecție"),
    ("composition", "compoziție"), ("distributor", "distribuitor"),
    ("leak", "scurgere"), ("small", "mic"),
    ("higher", "mai ridicat"), ("loss", "pierdere"),
    ("programming", "programare"), ("turbine", "turbină"),
    ("ratio", "raport"), ("all", "toate"),
    ("complete", "finalizat"), ("able", "capabil"),
    ("aborted", "întrerupt"), ("dual", "dublu"),
    ("absolute", "absolut"), ("transition", "tranziție"),
    ("demand", "cerere"), ("programmed", "programat"),
    ("pull", "atragere"), ("relief", "descărcare"),
    ("match", "corespund"), ("enable", "activare"),
    ("axle", "punte"), ("tire", "anvelopă"),
    ("acceptable", "acceptabil"), ("starter", "demaror"),
    ("stepping", "pas cu pas"), ("interlock", "interblocare"),
    ("shaft", "arbore"), ("automatic", "automat"),
    ("disengaged", "decuplat"), ("sender", "traductor"),
    ("acceleration", "accelerație"), ("threshold", "prag"),
    ("ajar", "deschis"), ("alarm", "alarmă"),
    ("tach", "tahometru"), ("wash", "spălare"),
    ("punch", "perforare"), ("hood", "capotă"),
    ("direction", "direcție"), ("keypad", "tastatură"),
    ("panic", "panică"), ("tamper", "manipulare neautorizată"),
    ("clear", "ștergere"), ("safing", "siguranță"),
    ("cargo", "portbagaj"), ("navigation", "navigație"),
    ("disc", "disc"), ("passengers", "pasager"),
    ("overheat", "supraîncălzire"), ("released", "eliberat"),
    ("comparison", "comparație"), ("transducer", "traductor"),
    ("phase", "fază"), ("problem", "problemă"),
    ("sounder", "avertizor sonor"), ("charging", "încărcare"),
    ("gate", "poartă"), ("legislated", "reglementat"),
    ("diagnostics", "diagnoză"), ("motion", "mișcare"),
    ("audible", "sonor"), ("warnings", "avertizări"),
    ("lamps", "lămpi"), ("environment", "mediu"),
    ("bus", "magistrală"), ("reached", "atins"),
    ("excessive", "excesiv"), ("activated", "activat"),
    ("please", "verificați"), ("pad", "plăcuță"),
    ("erratic", "neregulat"), ("warm", "încălzire"),
    ("charge", "încărcare"), ("coast", "rulare liberă"),
    ("systems", "sisteme"), ("second", "a doua"),
    ("faulty", "defect"), ("together", "împreună"),
    ("damage", "deteriorare"), ("spare", "rezervă"),
    ("downstream", "aval"), ("operational", "funcțional"),
    ("does", ""), ("disabled", "dezactivat"),
    ("by", "de"), ("recirculation", "recirculare"),
    ("cellular", "mobil"), ("double", "dublu"),
    ("mismatch", "neconcordanță"), ("receive", "recepționat"),
    ("what", "ceea ce"), ("was", "a fost"),
    ("receiver", "receptor"), ("cable", "cablu"),
    ("latch", "zăvor"), ("detent", "opritor"),
    ("shutdown", "oprire"), ("flame", "flacără"),
    ("fog", "ceață"), ("occupant", "ocupant"),
    ("child", "copil"), ("unlatch", "deblocare"),
    ("dumping", "evacuare"), ("exceeds", "depășește"),
    ("maximum", "maxim"), ("functions", "funcții"),
    ("temporarily", "temporar"), ("yaw", "girație"),
    ("booster", "amplificator"), ("compress", "compresie"),
    ("track", "șină"), ("energy", "energie"),
    ("telltales", "martori"), ("compact", "compact"),
    ("failure", "defecțiune"), ("malfunction", "funcționare defectuoasă"),
    ("fault", "defect"), ("sensor", "senzor"), ("switch", "comutator"),
    ("solenoid", "electrovalvă"), ("relay", "releu"), ("motor", "motor"),
    ("actuator", "actuator"), ("driver", "comandă"), ("module", "modul"),
    ("control", "comandă"), ("circuit", "circuit"), ("signal", "semnal"),
    ("input", "intrare"), ("output", "ieșire"), ("feedback", "răspuns"),
    ("battery", "baterie"), ("ground", "masă"), ("power", "alimentare"),
    ("supply", "alimentare"), ("voltage", "tensiune"), ("current", "curent"),
    ("open", "întrerupt"), ("short", "scurtcircuit"), ("intermittent", "intermitent"),
    ("missing", "lipsă"), ("invalid", "nevalid"), ("incorrect", "incorect"),
    ("implausible", "neplauzibil"), ("detected", "detectat"), ("stuck", "blocat"),
    ("low", "scăzut"), ("high", "ridicat"), ("range", "domeniu"),
    ("performance", "performanță"), ("system", "sistem"), ("data", "date"),
    ("communication", "comunicație"), ("request", "cerere"),
    ("pressure", "presiune"), ("temperature", "temperatură"),
    ("position", "poziție"), ("speed", "viteză"), ("level", "nivel"),
    ("flow", "debit"), ("timing", "sincronizare"), ("air", "aer"),
    ("fuel", "combustibil"), ("oil", "ulei"), ("coolant", "lichid de răcire"),
    ("exhaust", "evacuare"), ("intake", "admisie"), ("emission", "emisii"),
    ("engine", "motor"), ("transmission", "transmisie"), ("clutch", "ambreiaj"),
    ("brake", "frână"), ("steering", "direcție"), ("suspension", "suspensie"),
    ("wheel", "roată"), ("vehicle", "vehicul"), ("door", "ușă"),
    ("window", "geam"), ("mirror", "oglindă"), ("lamp", "lampă"),
    ("heater", "încălzitor"), ("blower", "ventilator habitaclu"),
    ("pump", "pompă"), ("valve", "supapă"), ("injector", "injector"),
    ("coil", "bobină"), ("cylinder", "cilindru"), ("bank", "banc"),
    ("front", "față"), ("rear", "spate"), ("left", "stânga"),
    ("right", "dreapta"), ("primary", "primar"), ("secondary", "secundar"),
    ("internal", "intern"), ("external", "extern"), ("upper", "superior"),
    ("lower", "inferior"), ("locked", "blocat"), ("unlocked", "deblocat"),
    ("warning", "avertizare"), ("indicator", "indicator"), ("memory", "memorie"),
)

_PHRASE_PATTERNS = tuple(
    (re.compile(re.escape(source), re.IGNORECASE), target)
    for source, target in sorted(_PHRASES, key=lambda item: len(item[0]), reverse=True)
)
_WORD_PATTERNS = tuple(
    (re.compile(rf"\b{re.escape(source)}\b", re.IGNORECASE), target)
    for source, target in _WORDS
)


def romanianize(text: str) -> str:
    """Traduce determinist terminologia tehnică uzuală, fără servicii online."""
    if not text:
        return ""
    result = str(text).replace("–", "-").replace("—", "-")
    for pattern, target in _PHRASE_PATTERNS:
        result = pattern.sub(target, result)
    for pattern, target in _WORD_PATTERNS:
        result = pattern.sub(target, result)
    result = re.sub(r"\s+", " ", result).strip()
    if result:
        result = result[0].upper() + result[1:]
    return result


def status_in_romanian(value: str) -> str:
    raw = (value or "").strip()
    low = raw.casefold()
    if not raw:
        return "Nespecificat"
    if "cannot be reached" in low or "no communication" in low:
        return "Fără comunicare"
    if "malfunction" in low or "defect" in low:
        return "Eroare"
    if low.startswith("ok"):
        return "OK"
    if low == "not confirmed":
        return "Neconfirmat"
    if low == "confirmed":
        return "Confirmat"
    replacements = {
        "intermittent": "Intermitent",
        "sporadic": "Sporadic",
        "static": "Static",
        "not confirmed": "Neconfirmat",
        "confirmed": "Confirmat",
        "pending": "În așteptare",
        "mil on": "Martor MIL aprins",
        "no signal": "Fără semnal",
        "implausible": "Neplauzibil",
    }
    parts: list[str] = []
    for source, target in replacements.items():
        if source == "confirmed" and "not confirmed" in low:
            continue
        if source in low and target not in parts:
            parts.append(target)
    return ", ".join(parts) if parts else romanianize(raw)
